from pathlib import Path


ROOT_DIR = Path(__file__).resolve().parents[1]
DATASET_PATH = ROOT_DIR / "conversations.csv"
PROCESSED_DIR = ROOT_DIR / "data" / "processed"

MESSAGES_PATH = PROCESSED_DIR / "messages.json"
TOPIC_CHECKPOINTS_PATH = PROCESSED_DIR / "topic_checkpoints.json"
HUNDRED_CHECKPOINTS_PATH = PROCESSED_DIR / "hundred_message_checkpoints.json"
PERSONA_PATH = PROCESSED_DIR / "persona.json"
RETRIEVAL_DOCUMENTS_PATH = PROCESSED_DIR / "retrieval_documents.json"

MIN_TOPIC_MESSAGES = 7
TOPIC_SIMILARITY_THRESHOLD = 0.06
TOPIC_WINDOW_SIZE = 8
SUMMARY_SENTENCE_LIMIT = 3
PERSONA_MAX_EVIDENCE_PER_ITEM = 3
PERSONA_MAX_ITEMS_PER_CATEGORY = 40
MESSAGE_CHUNK_SIZE = 20
MESSAGE_CHUNK_OVERLAP = 5
